### ISSUE TITLE
Hello, I test down the style conversion, the effect is not particularly good, there are some characters deformation, or some styles can not be migrated to the past, such as gipsy style, etc., why is this?

### ISSUE THREAD

**Issue by xuboot** [CrystalNeuro/visual-concept-translator#10]

**Comment by xuboot** [comment]
Given a picture, I am sd1.5 generated or other model generated character picture

**Comment by CrystalNeuro** [comment]
The default parameters do not fit every style type. Therefore, you should turn the parameters described in README to achieve better results. Character deformation can also be mitigated by turning the attention injection ratio. Changing the stable diffusion base model may also work.

**Comment by dmmSJTU** [comment]
@CrystalNeuro  @xuboot  你好，需要自己写测试代码吗？
