### ISSUE TITLE
Pytroch and Cuda versions

### ISSUE THREAD

**Issue by OrangeZz0331** [CrystalNeuro/visual-concept-translator#14]
Your paper is excellent！
But during runtime, I encountered the following error message:
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

I wonder if it's an issue with the PyTorch and Cuda versions, so I want to know about your version.
Thank you！

**Comment by OrangeZz0331** [comment]
And I want to know “concept_embedding_num”how should this parameter be set？

**Comment by longmans** [comment]
I'm running with cuda 12.2, it works with:

accelerate               0.15.0
attrs                    20.1.0
datasets                 2.10.1
diffusers                0.10.1
numpy                    1.22.1
opencv-python            4.7.0.72
protobuf                 3.20.0
requests                 2.29.0
scipy                    1.11.4
torch                    2.3.0
torchaudio               2.3.0
torchvision              0.18.0
tqdm                     4.64.1
transformers             4.41.1

**Comment by OrangeZz0331** [comment]
Thank you very much!
