### ISSUE TITLE
is "/home/liuzuhao/stable-diffusion-v1-5"  represent pretrained model from multi_concept_inversion?

### ISSUE THREAD

**Issue by ke0224** [CrystalNeuro/visual-concept-translator#2]
If this is the case, how can i load pretrained in func main()?

**Comment by CrystalNeuro** [comment]
Thanks for your check! This is a problem we have missed. Actually, you can use any Huggingface pre-trained model to replace that path. We have fixed this code error by introducing "pretrained_model_name_or_path" argument to replace the incorrect loading path. Thank you!
