### ISSUE TITLE
How much time is required 

### ISSUE THREAD

**Issue by howardgriffin** [CrystalNeuro/visual-concept-translator#3]
Hi ,I wonder how much time is required when I use one-shot guidance on A100 GPU

**Comment by CrystalNeuro** [comment]
That depends on the "max_train_steps" you select. Lower values such as 50 or 100 require several minutes. But some concepts may need large training steps such as 500, and this takes about 20-30 minutes. So you can start from a low training step, if the results are unsatisfactory, you can raise it.
