### ISSUE TITLE
what is it meaning??? 

### ISSUE THREAD

**Issue by Johnson-yue** [CrystalNeuro/visual-concept-translator#5]
https://github.com/CrystalNeuro/visual-concept-translator/blob/85813a903c0a4e44f322c2132a9de8a244b6e4a3/new_scheduling_ddpm.py#L131

when I using diffusers == 0.20.0 ,it always raise a ValueError .
So I remove it  , and  sd can be finetune.

**Comment by CrystalNeuro** [comment]
It is recommended to install the specified version in requirements.txt. Because update of diffusers is large and many old features are deprecated, so the overall functionality of the code cannot be guaranteed with the lasted diffusers installed.

**Comment by Johnson-yue** [comment]
It is means that  only using diffusers==0.10.1  can get the same performance as paper？

**Comment by CrystalNeuro** [comment]
You may delete that line and try to use the other diffusers versions. Actually, we found the conflict after upgrading to a specific version because the later version deletes some of its old features. However, if you do not find any conflict and your code runs well, I think you can get the paper performance.

**Comment by Johnson-yue** [comment]
I using diffusers == 0.20.0 without this line. It can run well without any problem, But the performance is bad  

Input-content :  examples/content_image/01.png | Input-concept :  examples/concept_image/08.png
![01_08](https://github.com/CrystalNeuro/visual-concept-translator/assets/10268274/7b295c1a-594c-47ce-8f19-b467397cb73d)
Input-content :  examples/content_image/02.png | Input-concept :  examples/concept_image/08.png
![02_08](https://github.com/CrystalNeuro/visual-concept-translator/assets/10268274/d236537e-4654-4cd5-8c12-5da7006c41cf)
Input-content :  examples/content_image/03.png | Input-concept :  examples/concept_image/08.png
![03_08](https://github.com/CrystalNeuro/visual-concept-translator/assets/10268274/0be6aa9d-6e3a-45d9-a3d3-00e0f8364ed7)
Input-content :  examples/content_image/04.png | Input-concept :  examples/concept_image/08.png
![04_08](https://github.com/CrystalNeuro/visual-concept-translator/assets/10268274/5ae29e11-a804-4c5b-9e9e-186b2671ba1b)
Input-content :  examples/content_image/05.png | Input-concept :  examples/concept_image/08.png
![05_08](https://github.com/CrystalNeuro/visual-concept-translator/assets/10268274/c5a01a0b-18bf-4f87-a365-219d79051914)
Input-content :  examples/content_image/06.png | Input-concept :  examples/concept_image/08.png
![06_08](https://github.com/CrystalNeuro/visual-concept-translator/assets/10268274/0350df21-9a60-42de-a4ca-0ddca24cf50e)
Input-content :  examples/content_image/07.png | Input-concept :  examples/concept_image/08.png
![07_08](https://github.com/CrystalNeuro/visual-concept-translator/assets/10268274/2bd02157-7773-4765-9c49-3eaa6d46adad)
Input-content :  examples/content_image/08.png | Input-concept :  examples/concept_image/08.png
![08_08](https://github.com/CrystalNeuro/visual-concept-translator/assets/10268274/54879771-42c8-4d4a-ae68-ba19c4f86678)
Input-content :  examples/content_image/09.png | Input-concept :  examples/concept_image/08.png
![09_08](https://github.com/CrystalNeuro/visual-concept-translator/assets/10268274/83adcf63-b299-495d-9599-58ee5aef142c)
Input-content :  examples/content_image/10.png | Input-concept :  examples/concept_image/08.png
![10_08](https://github.com/CrystalNeuro/visual-concept-translator/assets/10268274/6b6a6e37-8b34-49c6-bc7a-f620d588ef92)
Input-content :  examples/content_image/11.png | Input-concept :  examples/concept_image/08.png
![11_08](https://github.com/CrystalNeuro/visual-concept-translator/assets/10268274/fa130219-8efc-49cb-a129-350788267722)
Input-content :  examples/content_image/12.png | Input-concept :  examples/concept_image/08.png
![12_08](https://github.com/CrystalNeuro/visual-concept-translator/assets/10268274/e475d444-315e-4a47-8eb2-4d3aaa01e340)
Input-content :  examples/content_image/13.png | Input-concept :  examples/concept_image/08.png
![13_08](https://github.com/CrystalNeuro/visual-concept-translator/assets/10268274/f28982e4-a3d5-43d8-9a68-4682bde38722)
Input-content :  examples/content_image/14.png | Input-concept :  examples/concept_image/08.png
![14_08](https://github.com/CrystalNeuro/visual-concept-translator/assets/10268274/5e592ba5-b3e5-43b2-bed5-36497d9b9cc3)

-------------
train-config:

```
accelerate launch main.py \
    --concept_image_dir="./examples/concept_image" \
    --content_image_dir="./examples/content_image" \
    --output_image_path="./outputs" \
    --pretrained_model_name_or_path="/path/to/Runwayml_stable-diffusion-v1-5" \
    --initializer_token="girl" \
    --max_train_steps=500 \
    --concept_embedding_num=3 \
    --cross_attention_injection_ratio=0.2 \
    --self_attention_injection_ratio=0.9 \
    --use_l1 --allow_tf32
```

**Comment by CrystalNeuro** [comment]
Depending on what translation effect you want. If you think the concepts are not well-translated, you can decrease the self_attention_injection_ratio or cross_attention_injection_ratio, or increase the max_train_steps. If you think the content of the source image is not well preserved, you can increase the self_attention_injection_ratio or cross_attention_injection_ratio.
