### ISSUE TITLE
I downloaded the pre-training model locally and reported an error

### ISSUE THREAD

**Issue by xuboot** [CrystalNeuro/visual-concept-translator#7]
python  main.py  --concept_image_dir="./examples/concept_image" --content_image_dir="./examples/content_image" --pretrained_model_name_or_path="/root/autodl-tmp/visual-concept-translator/model" --output_image_path="./outputs" --initializer_token="girl" --max_train_steps=20  --concept_embedding_num=3 --cross_attention_injection_ratio=0.2  --self_attention_injection_ratio=0.9  --use_l1
/root/autodl-tmp/env/vct/lib/python3.8/site-packages/accelerate/accelerator.py:321: UserWarning: `log_with=tensorboard` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
08/28/2023 12:18:24 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda
Mixed precision type: no

Traceback (most recent call last):
  File "main.py", line 829, in <module>
    args = multi_concept_inversion()
  File "main.py", line 551, in multi_concept_inversion
    tokenizer = MultiTokenCLIPTokenizer.from_pretrained(args.pretrained_model_name_or_path, subfolder="tokenizer")
  File "/root/autodl-tmp/env/vct/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1788, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for '/root/autodl-tmp/visual-concept-translator/model'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/root/autodl-tmp/visual-concept-translator/model' is the correct path to a directory containing all relevant files for a MultiTokenCLIPTokenizer tokenizer.

**Comment by CrystalNeuro** [comment]
It seems that the model cannot find the "tokenizer" subfolder of your downloaded model. Please make sure the "pretrained_model_name_or_path" is the path containing the "tokenizer" subfolder just like the format of https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main.

**Comment by JQJQ2021** [comment]
> python main.py --concept_image_dir="./examples/concept_image" --content_image_dir="./examples/content_image" --pretrained_model_name_or_path="/root/autodl-tmp/visual-concept-translator/model" --output_image_path="./outputs" --initializer_token="girl" --max_train_steps=20 --concept_embedding_num=3 --cross_attention_injection_ratio=0.2 --self_attention_injection_ratio=0.9 --use_l1 /root/autodl-tmp/env/vct/lib/python3.8/site-packages/accelerate/accelerator.py:321: UserWarning: `log_with=tensorboard` was passed but no supported trackers are currently installed. warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.") 08/28/2023 12:18:24 - INFO - **main** - Distributed environment: NO Num processes: 1 Process index: 0 Local process index: 0 Device: cuda Mixed precision type: no
> 
> Traceback (most recent call last): File "main.py", line 829, in args = multi_concept_inversion() File "main.py", line 551, in multi_concept_inversion tokenizer = MultiTokenCLIPTokenizer.from_pretrained(args.pretrained_model_name_or_path, subfolder="tokenizer") File "/root/autodl-tmp/env/vct/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1788, in from_pretrained raise EnvironmentError( OSError: Can't load tokenizer for '/root/autodl-tmp/visual-concept-translator/model'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/root/autodl-tmp/visual-concept-translator/model' is the correct path to a directory containing all relevant files for a MultiTokenCLIPTokenizer tokenizer.

Have you solved this problem? I have the same problem as you. 
accelerate launch main.py \
    --concept_image_dir="./examples/concept_image" \
    --content_image_dir="./examples/content_image" \
    --pretrained_model_name_or_path="/put/your/downloaded/huggingface/model"
    --output_image_path="./outputs" \
    --initializer_token="girl" \
    --max_train_steps=500 \
    --concept_embedding_num=3 \
    --cross_attention_injection_ratio=0.2 \
    --self_attention_injection_ratio=0.9 \
    --use_l1
    
   To avoid the loading error or repeated downloads, it is recommended to download the pre-trained huggingface model such as [stable-diffusion-v1-5](https://huggingface.co/runwayml/stable-diffusion-v1-5) to local. Then put the downloaded path into pretrained_model_name_or_path.
   
   **I'm not sure what the author means. Should I put the .ckpt file in this path, or should I put the entire runwayml/stable-diffusion-v1-5 repository in this path?**

That is https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main，right?
@xuboot @CrystalNeuro

**Comment by gustn9609** [comment]
@JQJQ2021 
Did you solve it?
I have the same error and same question.
